# Generated by Django 4.0.2 on 2022-07-04 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeapp', '0004_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='feedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.FloatField()),
                ('s2', models.FloatField()),
                ('s3', models.FloatField()),
                ('s4', models.FloatField()),
                ('s5', models.FloatField()),
                ('s6', models.FloatField()),
                ('total', models.FloatField()),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feeapp.course')),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feeapp.student')),
            ],
        ),
    ]
