# Generated by Django 4.0.2 on 2022-07-04 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0005_alter_student_user_feedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedetails',
            name='cid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='sid',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
