# Generated by Django 4.0.2 on 2022-07-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0007_remove_feedetails_cid_remove_feedetails_sid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedetails',
        ),
    ]
