# Generated by Django 4.0.2 on 2022-07-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0008_delete_feedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('couid', models.IntegerField()),
            ],
        ),
    ]
