# Generated by Django 4.0.2 on 2022-07-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0009_fees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fees',
        ),
    ]
